### ISSUE TITLE
[BUG] quotes command 

### ISSUE THREAD

**Issue by kpatino** [kpatino/jamal_bot#6]
**Describe the bug**
when issuing `jamal quotes` and responding with the correct 

**To Reproduce**
1. issue `jamal quotes`
2. respond with the correct person who said the quote
3. jamal responds that you are wrong

**Expected behavior**
I am right!!!

**Environment Information (please complete the following information):**
Arch and Debian
Python 3.9.2 and Python 3.8
Discord.py-1.7.2

**Comment by danger-ahead** [comment]
I can help. Please consider assigning me
